// =======================================================================
// БАЗА ПРИЁМОВ POKEMON
// Этап 1: стартовый централизованный справочник
// =======================================================================

const MOVES = {
    "tackle": {
        id: "tackle",
        name: "Удар",
        description: "Обычная физическая атака без дополнительного эффекта.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "vine-whip": {
        id: "vine-whip",
        name: "Семенной луч",
        description: "Покемон бьёт врага лозой.",
        type: "grass",
        power: 45,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "growl": {
        id: "growl",
        name: "Рык",
        description: "Понижает атаку противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_attack"
    },
    "ember": {
        id: "ember",
        name: "Уголёк",
        description: "Небольшая огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "water-gun": {
        id: "water-gun",
        name: "Водяной пистолет",
        description: "Атака струёй воды.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "thunder-shock": {
        id: "thunder-shock",
        name: "Искрошок",
        description: "Электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "scratch": {
        id: "scratch",
        name: "Царапина",
        description: "Покемон царапает врага когтями.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "leer": {
        id: "leer",
        name: "Злобный взгляд",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    },
    "bite": {
        id: "bite",
        name: "Укус",
        description: "Кусает противника. Может заставить дрогнуть.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "quick-attack": {
        id: "quick-attack",
        name: "Быстрая атака",
        description: "Атакует раньше обычного.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 1,
        target: "enemy",
        effect: "damage"
    },
    "razor-leaf": {
        id: "razor-leaf",
        name: "Острый лист",
        description: "Режет врага острыми листьями.",
        type: "grass",
        power: 55,
        accuracy: 95,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "flame-wheel": {
        id: "flame-wheel",
        name: "Огненное колесо",
        description: "Атака в огненном вращении. Может вызвать ожог.",
        type: "fire",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "bubble": {
        id: "bubble",
        name: "Пузырь",
        description: "Атака пузырями. Может понизить скорость.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_speed_chance"
    },
    "thunderbolt": {
        id: "thunderbolt",
        name: "Удар молнии",
        description: "Мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "fire-blast": {
        id: "fire-blast",
        name: "Огненный взрыв",
        description: "Очень мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 110,
        accuracy: 85,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "hydro-pump": {
        id: "hydro-pump",
        name: "Гидронасос",
        description: "Очень мощная водная атака.",
        type: "water",
        power: 110,
        accuracy: 80,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "solar-beam": {
        id: "solar-beam",
        name: "Солнечный луч",
        description: "Мощная травяная атака.",
        type: "grass",
        power: 120,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "psychic": {
        id: "psychic",
        name: "Психический",
        description: "Мощная психическая атака. Может понизить спецзащиту.",
        type: "psychic",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "shadow-ball": {
        id: "shadow-ball",
        name: "Теневой шар",
        description: "Атака теневой сферой. Может понизить спецзащиту.",
        type: "ghost",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "hyper-beam": {
        id: "hyper-beam",
        name: "Гиперлуч",
        description: "Очень мощная атака. После неё нужен отдых.",
        type: "normal",
        power: 150,
        accuracy: 90,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_recharge"
    },
    "flamethrower": {
        id: "flamethrower",
        name: "Огнемёт",
        description: "Мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "ice-beam": {
        id: "ice-beam",
        name: "Ледяной луч",
        description: "Мощная ледяная атака. Может заморозить.",
        type: "ice",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "thunder": {
        id: "thunder",
        name: "Гром",
        description: "Очень мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 110,
        accuracy: 70,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "earthquake": {
        id: "earthquake",
        name: "Землетрясение",
        description: "Мощная атака землёй.",
        type: "ground",
        power: 100,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "surf": {
        id: "surf",
        name: "Прилив",
        description: "Мощная водная атака.",
        type: "water",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "fly": {
        id: "fly",
        name: "Полёт",
        description: "Атака с взлётом и ударом.",
        type: "flying",
        power: 90,
        accuracy: 95,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "dig": {
        id: "dig",
        name: "Копание",
        description: "Атака с уходом под землю.",
        type: "ground",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "strength": {
        id: "strength",
        name: "Сила",
        description: "Мощная физическая атака.",
        type: "normal",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "cut": {
        id: "cut",
        name: "Разрез",
        description: "Режущая обычная атака.",
        type: "normal",
        power: 50,
        accuracy: 95,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "rock-smash": {
        id: "rock-smash",
        name: "Крушение камня",
        description: "Физическая атака. Может понизить защиту.",
        type: "fighting",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "shadow-punch": {
        id: "shadow-punch",
        name: "Теневой удар",
        description: "Теневая атака, которая не промахивается.",
        type: "ghost",
        power: 60,
        accuracy: 101,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    },
    "dragon-claw": {
        id: "dragon-claw",
        name: "Коготь дракона",
        description: "Сильная драконья атака.",
        type: "dragon",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "dark-pulse": {
        id: "dark-pulse",
        name: "Тёмный импульс",
        description: "Тёмная атака. Может заставить дрогнуть.",
        type: "dark",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "dazzling-gleam": {
        id: "dazzling-gleam",
        name: "Ослепительное сияние",
        description: "Атака волшебным светом.",
        type: "fairy",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "moonblast": {
        id: "moonblast",
        name: "Лунный взрыв",
        description: "Мощная волшебная атака. Может понизить спецатаку.",
        type: "fairy",
        power: 95,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spatk_chance"
    },
    "play-rough": {
        id: "play-rough",
        name: "Игривый удар",
        description: "Может понизить атаку противника.",
        type: "fairy",
        power: 90,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_attack_chance"
    },
    "x-scissor": {
        id: "x-scissor",
        name: "Икс-ножницы",
        description: "Сильная режущая атака.",
        type: "bug",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "bug-buzz": {
        id: "bug-buzz",
        name: "Жужжание",
        description: "Звуковая атака насекомого. Может понизить спецзащиту.",
        type: "bug",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "poison-jab": {
        id: "poison-jab",
        name: "Ядовитый укол",
        description: "Может отравить противника.",
        type: "poison",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "sludge-bomb": {
        id: "sludge-bomb",
        name: "Грязевая бомба",
        description: "Может отравить противника.",
        type: "poison",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "steel-wing": {
        id: "steel-wing",
        name: "Стальное крыло",
        description: "Может повысить защиту пользователя.",
        type: "steel",
        power: 70,
        accuracy: 90,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_defense_chance"
    },
    "iron-tail": {
        id: "iron-tail",
        name: "Железный хвост",
        description: "Может понизить защиту противника.",
        type: "steel",
        power: 100,
        accuracy: 75,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "rock-slide": {
        id: "rock-slide",
        name: "Камнепад",
        description: "Может заставить противника дрогнуть.",
        type: "rock",
        power: 75,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "stone-edge": {
        id: "stone-edge",
        name: "Каменный край",
        description: "Сильная каменная атака.",
        type: "rock",
        power: 100,
        accuracy: 80,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "slam": {
        id: "slam",
        name: "Шлепок",
        description: "Сильная обычная атака.",
        type: "normal",
        power: 80,
        accuracy: 75,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "double-kick": {
        id: "double-kick",
        name: "Двойной удар",
        description: "Бьёт два раза подряд.",
        type: "fighting",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_2"
    },
    "tail-whip": {
        id: "tail-whip",
        name: "Виляние хвостом",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    }
};


Object.assign(MOVES, {
    "absorb": {
        id: "absorb",
        name: "Поглощение",
        description: "Атакует и восстанавливает часть нанесённого урона.",
        type: "grass",
        power: 20,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "drain"
    },
    "acid": {
        id: "acid",
        name: "Кислота",
        description: "Может понизить спецзащиту противника.",
        type: "poison",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "acid-armor": {
        id: "acid-armor",
        name: "Кислотная броня",
        description: "Сильно повышает защиту пользователя.",
        type: "poison",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_defense_2"
    },
    "agility": {
        id: "agility",
        name: "Проворство",
        description: "Сильно повышает скорость пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "self",
        effect: "raise_speed_2"
    },
    "amnesia": {
        id: "amnesia",
        name: "Амнезия",
        description: "Сильно повышает спецзащиту пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_spdef_2"
    },
    "ancient-power": {
        id: "ancient-power",
        name: "Древняя сила",
        description: "Может повысить все основные характеристики пользователя.",
        type: "rock",
        power: 60,
        accuracy: 100,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_all_chance"
    },
    "aromatherapy": {
        id: "aromatherapy",
        name: "Ароматерапия",
        description: "Лечит статусные состояния команды.",
        type: "grass",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "party",
        effect: "heal_party_status"
    },
    "assurance": {
        id: "assurance",
        name: "Возмездие",
        description: "Сильнее бьёт, если цель уже получала урон в этом ходу.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "conditional_damage"
    },
    "astonish": {
        id: "astonish",
        name: "Изумление",
        description: "Может заставить противника дрогнуть.",
        type: "ghost",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "aurora-beam": {
        id: "aurora-beam",
        name: "Сияющий луч",
        description: "Может понизить атаку противника.",
        type: "ice",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_attack_chance"
    },
    "beat-up": {
        id: "beat-up",
        name: "Избиение",
        description: "Несколько покемонов команды наносят серию ударов.",
        type: "dark",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_party"
    },
    "belch": {
        id: "belch",
        name: "Отрыжка",
        description: "Мощная атака, доступная после использования ягоды.",
        type: "poison",
        power: 120,
        accuracy: 90,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "conditional_damage"
    },
    "bide": {
        id: "bide",
        name: "Выжидание",
        description: "Копит полученный урон и затем возвращает его.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "physical",
        max_pp: 10,
        priority: 1,
        target: "enemy",
        effect: "counter_delayed"
    },
    "bind": {
        id: "bind",
        name: "Сжатие",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "normal",
        power: 15,
        accuracy: 85,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "blizzard": {
        id: "blizzard",
        name: "Метель",
        description: "Мощная ледяная атака. Может заморозить.",
        type: "ice",
        power: 110,
        accuracy: 70,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "body-slam": {
        id: "body-slam",
        name: "Толчок телом",
        description: "Может вызвать паралич.",
        type: "normal",
        power: 85,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "bubble-beam": {
        id: "bubble-beam",
        name: "Пузырьковый луч",
        description: "Может понизить скорость противника.",
        type: "water",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_speed_chance"
    },
    "bug-bite": {
        id: "bug-bite",
        name: "Укус жука",
        description: "Если у цели есть ягода, пользователь может её съесть.",
        type: "bug",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_berry_steal"
    },
    "charge-beam": {
        id: "charge-beam",
        name: "Зарядный луч",
        description: "Может повысить спецатаку пользователя.",
        type: "electric",
        power: 50,
        accuracy: 90,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_spatk_chance"
    },
    "charm": {
        id: "charm",
        name: "Очарование",
        description: "Сильно понижает атаку противника.",
        type: "fairy",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "lower_attack_2"
    },
    "clamp": {
        id: "clamp",
        name: "Зажим",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "water",
        power: 35,
        accuracy: 85,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "comet-punch": {
        id: "comet-punch",
        name: "Кометный удар",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 18,
        accuracy: 85,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "confuse-ray": {
        id: "confuse-ray",
        name: "Луч замешательства",
        description: "Приводит цель в замешательство.",
        type: "ghost",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "confuse"
    },
    "confusion": {
        id: "confusion",
        name: "Замешательство",
        description: "Психическая атака. Может вызвать замешательство.",
        type: "psychic",
        power: 50,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_confuse_chance"
    },
    "cosmic-power": {
        id: "cosmic-power",
        name: "Космическая сила",
        description: "Повышает защиту и спецзащиту пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_defense_spdef"
    },
    "cotton-spore": {
        id: "cotton-spore",
        name: "Хлопковая пыльца",
        description: "Сильно понижает скорость противника.",
        type: "grass",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_speed_2"
    },
    "counter": {
        id: "counter",
        name: "Контрудар",
        description: "Возвращает физический урон с усилением.",
        type: "fighting",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: -5,
        target: "enemy",
        effect: "counter_physical"
    },
    "crunch": {
        id: "crunch",
        name: "Хруст",
        description: "Может понизить защиту противника.",
        type: "dark",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "curse": {
        id: "curse",
        name: "Проклятие",
        description: "Особый эффект: усиливает пользователя или проклинает цель.",
        type: "ghost",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "special",
        effect: "curse"
    },
    "defense-curl": {
        id: "defense-curl",
        name: "Защитное сворачивание",
        description: "Повышает защиту пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "self",
        effect: "raise_defense"
    },
    "destiny-bond": {
        id: "destiny-bond",
        name: "Связь судеб",
        description: "Если пользователь упадёт, противник тоже может пасть.",
        type: "ghost",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "self",
        effect: "destiny_bond"
    },
    "disable": {
        id: "disable",
        name: "Блокировка",
        description: "Временно запрещает последний использованный приём цели.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "disable"
    },
    "double-edge": {
        id: "double-edge",
        name: "Двойной край",
        description: "Сильная атака с отдачей.",
        type: "normal",
        power: 120,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_recoil"
    },
    "double-slap": {
        id: "double-slap",
        name: "Двойная пощёчина",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 15,
        accuracy: 85,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "double-team": {
        id: "double-team",
        name: "Двойник",
        description: "Повышает уклонение пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "self",
        effect: "raise_evasion"
    },
    "dragon-breath": {
        id: "dragon-breath",
        name: "Дыхание дракона",
        description: "Может вызвать паралич.",
        type: "dragon",
        power: 60,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "dragon-rage": {
        id: "dragon-rage",
        name: "Ярость дракона",
        description: "Всегда наносит фиксированный урон.",
        type: "dragon",
        power: 0,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "fixed_40"
    },
    "dream-eater": {
        id: "dream-eater",
        name: "Пожиратель снов",
        description: "Работает только по спящей цели и восстанавливает HP.",
        type: "psychic",
        power: 100,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "dream_eater"
    },
    "drill-peck": {
        id: "drill-peck",
        name: "Сверлящий клюв",
        description: "Сильная летающая атака.",
        type: "flying",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "encore": {
        id: "encore",
        name: "Бис",
        description: "Заставляет цель повторять один и тот же приём.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "encore"
    },
    "explosion": {
        id: "explosion",
        name: "Взрыв",
        description: "Очень мощная атака, после которой пользователь падает.",
        type: "normal",
        power: 250,
        accuracy: 100,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "self_destruct"
    },
    "fake-out": {
        id: "fake-out",
        name: "Обманка",
        description: "Срабатывает в начале выхода и может заставить дрогнуть.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 3,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "feint-attack": {
        id: "feint-attack",
        name: "Подлый удар",
        description: "Не промахивается.",
        type: "dark",
        power: 60,
        accuracy: 101,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    }
});

function getMoveDescription(moveId) {
    if (!MOVES[moveId]) return "Описание отсутствует.";
    return MOVES[moveId].description || "Описание отсутствует.";
}
