// =======================================================================
// БАЗА ПРИЁМОВ POKEMON
// Этап 1: стартовый централизованный справочник
// =======================================================================

const MOVES = {
    "tackle": {
        id: "tackle",
        name: "Удар",
        description: "Обычная физическая атака без дополнительного эффекта.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "vine-whip": {
        id: "vine-whip",
        name: "Семенной луч",
        description: "Покемон бьёт врага лозой.",
        type: "grass",
        power: 45,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "growl": {
        id: "growl",
        name: "Рык",
        description: "Понижает атаку противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_attack"
    },
    "ember": {
        id: "ember",
        name: "Уголёк",
        description: "Небольшая огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "water-gun": {
        id: "water-gun",
        name: "Водяной пистолет",
        description: "Атака струёй воды.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "thunder-shock": {
        id: "thunder-shock",
        name: "Искрошок",
        description: "Электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "scratch": {
        id: "scratch",
        name: "Царапина",
        description: "Покемон царапает врага когтями.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "leer": {
        id: "leer",
        name: "Злобный взгляд",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    },
    "bite": {
        id: "bite",
        name: "Укус",
        description: "Кусает противника. Может заставить дрогнуть.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "quick-attack": {
        id: "quick-attack",
        name: "Быстрая атака",
        description: "Атакует раньше обычного.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 1,
        target: "enemy",
        effect: "damage"
    },
    "razor-leaf": {
        id: "razor-leaf",
        name: "Острый лист",
        description: "Режет врага острыми листьями.",
        type: "grass",
        power: 55,
        accuracy: 95,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "flame-wheel": {
        id: "flame-wheel",
        name: "Огненное колесо",
        description: "Атака в огненном вращении. Может вызвать ожог.",
        type: "fire",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "bubble": {
        id: "bubble",
        name: "Пузырь",
        description: "Атака пузырями. Может понизить скорость.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_speed_chance"
    },
    "thunderbolt": {
        id: "thunderbolt",
        name: "Удар молнии",
        description: "Мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "fire-blast": {
        id: "fire-blast",
        name: "Огненный взрыв",
        description: "Очень мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 110,
        accuracy: 85,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "hydro-pump": {
        id: "hydro-pump",
        name: "Гидронасос",
        description: "Очень мощная водная атака.",
        type: "water",
        power: 110,
        accuracy: 80,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "solar-beam": {
        id: "solar-beam",
        name: "Солнечный луч",
        description: "Мощная травяная атака.",
        type: "grass",
        power: 120,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "psychic": {
        id: "psychic",
        name: "Психический",
        description: "Мощная психическая атака. Может понизить спецзащиту.",
        type: "psychic",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "shadow-ball": {
        id: "shadow-ball",
        name: "Теневой шар",
        description: "Атака теневой сферой. Может понизить спецзащиту.",
        type: "ghost",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "hyper-beam": {
        id: "hyper-beam",
        name: "Гиперлуч",
        description: "Очень мощная атака. После неё нужен отдых.",
        type: "normal",
        power: 150,
        accuracy: 90,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_recharge"
    },
    "flamethrower": {
        id: "flamethrower",
        name: "Огнемёт",
        description: "Мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "ice-beam": {
        id: "ice-beam",
        name: "Ледяной луч",
        description: "Мощная ледяная атака. Может заморозить.",
        type: "ice",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "thunder": {
        id: "thunder",
        name: "Гром",
        description: "Очень мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 110,
        accuracy: 70,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "earthquake": {
        id: "earthquake",
        name: "Землетрясение",
        description: "Мощная атака землёй.",
        type: "ground",
        power: 100,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "surf": {
        id: "surf",
        name: "Прилив",
        description: "Мощная водная атака.",
        type: "water",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "fly": {
        id: "fly",
        name: "Полёт",
        description: "Атака с взлётом и ударом.",
        type: "flying",
        power: 90,
        accuracy: 95,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "dig": {
        id: "dig",
        name: "Копание",
        description: "Атака с уходом под землю.",
        type: "ground",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "strength": {
        id: "strength",
        name: "Сила",
        description: "Мощная физическая атака.",
        type: "normal",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "cut": {
        id: "cut",
        name: "Разрез",
        description: "Режущая обычная атака.",
        type: "normal",
        power: 50,
        accuracy: 95,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "rock-smash": {
        id: "rock-smash",
        name: "Крушение камня",
        description: "Физическая атака. Может понизить защиту.",
        type: "fighting",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "shadow-punch": {
        id: "shadow-punch",
        name: "Теневой удар",
        description: "Теневая атака, которая не промахивается.",
        type: "ghost",
        power: 60,
        accuracy: 101,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    },
    "dragon-claw": {
        id: "dragon-claw",
        name: "Коготь дракона",
        description: "Сильная драконья атака.",
        type: "dragon",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "dark-pulse": {
        id: "dark-pulse",
        name: "Тёмный импульс",
        description: "Тёмная атака. Может заставить дрогнуть.",
        type: "dark",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "dazzling-gleam": {
        id: "dazzling-gleam",
        name: "Ослепительное сияние",
        description: "Атака волшебным светом.",
        type: "fairy",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "moonblast": {
        id: "moonblast",
        name: "Лунный взрыв",
        description: "Мощная волшебная атака. Может понизить спецатаку.",
        type: "fairy",
        power: 95,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spatk_chance"
    },
    "play-rough": {
        id: "play-rough",
        name: "Игривый удар",
        description: "Может понизить атаку противника.",
        type: "fairy",
        power: 90,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_attack_chance"
    },
    "x-scissor": {
        id: "x-scissor",
        name: "Икс-ножницы",
        description: "Сильная режущая атака.",
        type: "bug",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "bug-buzz": {
        id: "bug-buzz",
        name: "Жужжание",
        description: "Звуковая атака насекомого. Может понизить спецзащиту.",
        type: "bug",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "poison-jab": {
        id: "poison-jab",
        name: "Ядовитый укол",
        description: "Может отравить противника.",
        type: "poison",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "sludge-bomb": {
        id: "sludge-bomb",
        name: "Грязевая бомба",
        description: "Может отравить противника.",
        type: "poison",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "steel-wing": {
        id: "steel-wing",
        name: "Стальное крыло",
        description: "Может повысить защиту пользователя.",
        type: "steel",
        power: 70,
        accuracy: 90,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_defense_chance"
    },
    "iron-tail": {
        id: "iron-tail",
        name: "Железный хвост",
        description: "Может понизить защиту противника.",
        type: "steel",
        power: 100,
        accuracy: 75,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "rock-slide": {
        id: "rock-slide",
        name: "Камнепад",
        description: "Может заставить противника дрогнуть.",
        type: "rock",
        power: 75,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "stone-edge": {
        id: "stone-edge",
        name: "Каменный край",
        description: "Сильная каменная атака.",
        type: "rock",
        power: 100,
        accuracy: 80,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "slam": {
        id: "slam",
        name: "Шлепок",
        description: "Сильная обычная атака.",
        type: "normal",
        power: 80,
        accuracy: 75,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "double-kick": {
        id: "double-kick",
        name: "Двойной удар",
        description: "Бьёт два раза подряд.",
        type: "fighting",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_2"
    },
    "tail-whip": {
        id: "tail-whip",
        name: "Виляние хвостом",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    }
};


Object.assign(MOVES, {
    "absorb": {
        id: "absorb",
        name: "Поглощение",
        description: "Атакует и восстанавливает часть нанесённого урона.",
        type: "grass",
        power: 20,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "drain"
    },
    "acid": {
        id: "acid",
        name: "Кислота",
        description: "Может понизить спецзащиту противника.",
        type: "poison",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "acid-armor": {
        id: "acid-armor",
        name: "Кислотная броня",
        description: "Сильно повышает защиту пользователя.",
        type: "poison",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_defense_2"
    },
    "agility": {
        id: "agility",
        name: "Проворство",
        description: "Сильно повышает скорость пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "self",
        effect: "raise_speed_2"
    },
    "amnesia": {
        id: "amnesia",
        name: "Амнезия",
        description: "Сильно повышает спецзащиту пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_spdef_2"
    },
    "ancient-power": {
        id: "ancient-power",
        name: "Древняя сила",
        description: "Может повысить все основные характеристики пользователя.",
        type: "rock",
        power: 60,
        accuracy: 100,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_all_chance"
    },
    "aromatherapy": {
        id: "aromatherapy",
        name: "Ароматерапия",
        description: "Лечит статусные состояния команды.",
        type: "grass",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "party",
        effect: "heal_party_status"
    },
    "assurance": {
        id: "assurance",
        name: "Возмездие",
        description: "Сильнее бьёт, если цель уже получала урон в этом ходу.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "conditional_damage"
    },
    "astonish": {
        id: "astonish",
        name: "Изумление",
        description: "Может заставить противника дрогнуть.",
        type: "ghost",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "aurora-beam": {
        id: "aurora-beam",
        name: "Сияющий луч",
        description: "Может понизить атаку противника.",
        type: "ice",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_attack_chance"
    },
    "beat-up": {
        id: "beat-up",
        name: "Избиение",
        description: "Несколько покемонов команды наносят серию ударов.",
        type: "dark",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_party"
    },
    "belch": {
        id: "belch",
        name: "Отрыжка",
        description: "Мощная атака, доступная после использования ягоды.",
        type: "poison",
        power: 120,
        accuracy: 90,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "conditional_damage"
    },
    "bide": {
        id: "bide",
        name: "Выжидание",
        description: "Копит полученный урон и затем возвращает его.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "physical",
        max_pp: 10,
        priority: 1,
        target: "enemy",
        effect: "counter_delayed"
    },
    "bind": {
        id: "bind",
        name: "Сжатие",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "normal",
        power: 15,
        accuracy: 85,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "blizzard": {
        id: "blizzard",
        name: "Метель",
        description: "Мощная ледяная атака. Может заморозить.",
        type: "ice",
        power: 110,
        accuracy: 70,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "body-slam": {
        id: "body-slam",
        name: "Толчок телом",
        description: "Может вызвать паралич.",
        type: "normal",
        power: 85,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "bubble-beam": {
        id: "bubble-beam",
        name: "Пузырьковый луч",
        description: "Может понизить скорость противника.",
        type: "water",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_speed_chance"
    },
    "bug-bite": {
        id: "bug-bite",
        name: "Укус жука",
        description: "Если у цели есть ягода, пользователь может её съесть.",
        type: "bug",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_berry_steal"
    },
    "charge-beam": {
        id: "charge-beam",
        name: "Зарядный луч",
        description: "Может повысить спецатаку пользователя.",
        type: "electric",
        power: 50,
        accuracy: 90,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_spatk_chance"
    },
    "charm": {
        id: "charm",
        name: "Очарование",
        description: "Сильно понижает атаку противника.",
        type: "fairy",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "lower_attack_2"
    },
    "clamp": {
        id: "clamp",
        name: "Зажим",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "water",
        power: 35,
        accuracy: 85,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "comet-punch": {
        id: "comet-punch",
        name: "Кометный удар",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 18,
        accuracy: 85,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "confuse-ray": {
        id: "confuse-ray",
        name: "Луч замешательства",
        description: "Приводит цель в замешательство.",
        type: "ghost",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "confuse"
    },
    "confusion": {
        id: "confusion",
        name: "Замешательство",
        description: "Психическая атака. Может вызвать замешательство.",
        type: "psychic",
        power: 50,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_confuse_chance"
    },
    "cosmic-power": {
        id: "cosmic-power",
        name: "Космическая сила",
        description: "Повышает защиту и спецзащиту пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_defense_spdef"
    },
    "cotton-spore": {
        id: "cotton-spore",
        name: "Хлопковая пыльца",
        description: "Сильно понижает скорость противника.",
        type: "grass",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_speed_2"
    },
    "counter": {
        id: "counter",
        name: "Контрудар",
        description: "Возвращает физический урон с усилением.",
        type: "fighting",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: -5,
        target: "enemy",
        effect: "counter_physical"
    },
    "crunch": {
        id: "crunch",
        name: "Хруст",
        description: "Может понизить защиту противника.",
        type: "dark",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "curse": {
        id: "curse",
        name: "Проклятие",
        description: "Особый эффект: усиливает пользователя или проклинает цель.",
        type: "ghost",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "special",
        effect: "curse"
    },
    "defense-curl": {
        id: "defense-curl",
        name: "Защитное сворачивание",
        description: "Повышает защиту пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "self",
        effect: "raise_defense"
    },
    "destiny-bond": {
        id: "destiny-bond",
        name: "Связь судеб",
        description: "Если пользователь упадёт, противник тоже может пасть.",
        type: "ghost",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "self",
        effect: "destiny_bond"
    },
    "disable": {
        id: "disable",
        name: "Блокировка",
        description: "Временно запрещает последний использованный приём цели.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "disable"
    },
    "double-edge": {
        id: "double-edge",
        name: "Двойной край",
        description: "Сильная атака с отдачей.",
        type: "normal",
        power: 120,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_recoil"
    },
    "double-slap": {
        id: "double-slap",
        name: "Двойная пощёчина",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 15,
        accuracy: 85,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "double-team": {
        id: "double-team",
        name: "Двойник",
        description: "Повышает уклонение пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "self",
        effect: "raise_evasion"
    },
    "dragon-breath": {
        id: "dragon-breath",
        name: "Дыхание дракона",
        description: "Может вызвать паралич.",
        type: "dragon",
        power: 60,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "dragon-rage": {
        id: "dragon-rage",
        name: "Ярость дракона",
        description: "Всегда наносит фиксированный урон.",
        type: "dragon",
        power: 0,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "fixed_40"
    },
    "dream-eater": {
        id: "dream-eater",
        name: "Пожиратель снов",
        description: "Работает только по спящей цели и восстанавливает HP.",
        type: "psychic",
        power: 100,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "dream_eater"
    },
    "drill-peck": {
        id: "drill-peck",
        name: "Сверлящий клюв",
        description: "Сильная летающая атака.",
        type: "flying",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "encore": {
        id: "encore",
        name: "Бис",
        description: "Заставляет цель повторять один и тот же приём.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "encore"
    },
    "explosion": {
        id: "explosion",
        name: "Взрыв",
        description: "Очень мощная атака, после которой пользователь падает.",
        type: "normal",
        power: 250,
        accuracy: 100,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "self_destruct"
    },
    "fake-out": {
        id: "fake-out",
        name: "Обманка",
        description: "Срабатывает в начале выхода и может заставить дрогнуть.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 3,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "feint-attack": {
        id: "feint-attack",
        name: "Подлый удар",
        description: "Не промахивается.",
        type: "dark",
        power: 60,
        accuracy: 101,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    }
});


Object.assign(MOVES, {
    "fire-punch": {
        id: "fire-punch",
        name: "Огненный кулак",
        description: "Огненная атака кулаком. Может вызвать ожог.",
        type: "fire",
        power: 75,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "fire-spin": {
        id: "fire-spin",
        name: "Огненный вихрь",
        description: "Огненная атака, которая может удерживать цель несколько ходов.",
        type: "fire",
        power: 35,
        accuracy: 85,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "fissure": {
        id: "fissure",
        name: "Разлом",
        description: "При попадании мгновенно выводит цель из строя.",
        type: "ground",
        power: 0,
        accuracy: 30,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "ohko"
    },
    "flail": {
        id: "flail",
        name: "Барахтанье",
        description: "Чем меньше HP у пользователя, тем сильнее атака.",
        type: "normal",
        power: 1,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "low_hp_stronger"
    },
    "flame-burst": {
        id: "flame-burst",
        name: "Огненный всплеск",
        description: "Огненная атака взрывом пламени.",
        type: "fire",
        power: 70,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "focus-energy": {
        id: "focus-energy",
        name: "Сосредоточение",
        description: "Повышает шанс критического удара.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "self",
        effect: "raise_crit"
    },
    "foresight": {
        id: "foresight",
        name: "Предвидение",
        description: "Позволяет попасть по уклоняющейся или призрачной цели.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "identify_target"
    },
    "fury-attack": {
        id: "fury-attack",
        name: "Яростная атака",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 15,
        accuracy: 85,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "fury-cutter": {
        id: "fury-cutter",
        name: "Яростный рез",
        description: "Если использовать подряд, сила атаки растёт.",
        type: "bug",
        power: 40,
        accuracy: 95,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "successive_stronger"
    },
    "fury-swipes": {
        id: "fury-swipes",
        name: "Яростные когти",
        description: "Бьёт несколько раз подряд.",
        type: "normal",
        power: 18,
        accuracy: 80,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "giga-drain": {
        id: "giga-drain",
        name: "Гига-поглощение",
        description: "Поглощает HP противника и восстанавливает пользователя.",
        type: "grass",
        power: 75,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "drain"
    },
    "glare": {
        id: "glare",
        name: "Пристальный взгляд",
        description: "Парализует противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "paralyze"
    },
    "growth": {
        id: "growth",
        name: "Рост",
        description: "Повышает атаку и спецатаку пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_attack_spatk"
    },
    "guillotine": {
        id: "guillotine",
        name: "Гильотина",
        description: "При попадании мгновенно выводит цель из строя.",
        type: "normal",
        power: 0,
        accuracy: 30,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "ohko"
    },
    "gust": {
        id: "gust",
        name: "Порыв",
        description: "Лёгкая летающая атака.",
        type: "flying",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "harden": {
        id: "harden",
        name: "Отвердевание",
        description: "Повышает защиту пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "self",
        effect: "raise_defense"
    },
    "haze": {
        id: "haze",
        name: "Туман",
        description: "Сбрасывает изменения характеристик на поле.",
        type: "ice",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "field",
        effect: "reset_stats"
    },
    "headbutt": {
        id: "headbutt",
        name: "Удар головой",
        description: "Может заставить противника дрогнуть.",
        type: "normal",
        power: 70,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "helping-hand": {
        id: "helping-hand",
        name: "Рука помощи",
        description: "Усиливает атаку союзника.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 5,
        target: "ally",
        effect: "ally_boost"
    },
    "hidden-power": {
        id: "hidden-power",
        name: "Скрытая сила",
        description: "Тип приёма зависит от внутренних параметров покемона.",
        type: "normal",
        power: 60,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "variable_type_damage"
    },
    "high-jump-kick": {
        id: "high-jump-kick",
        name: "Высокий прыжковый удар",
        description: "Сильная атака. При промахе пользователь получает отдачу.",
        type: "fighting",
        power: 130,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_crash"
    },
    "horn-attack": {
        id: "horn-attack",
        name: "Роговая атака",
        description: "Обычная физическая атака рогом.",
        type: "normal",
        power: 65,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "horn-drill": {
        id: "horn-drill",
        name: "Роговое сверло",
        description: "При попадании мгновенно выводит цель из строя.",
        type: "normal",
        power: 0,
        accuracy: 30,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "ohko"
    },
    "hypnosis": {
        id: "hypnosis",
        name: "Гипноз",
        description: "Усыпляет противника.",
        type: "psychic",
        power: 0,
        accuracy: 60,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "sleep"
    },
    "ice-punch": {
        id: "ice-punch",
        name: "Ледяной кулак",
        description: "Ледяная атака кулаком. Может заморозить.",
        type: "ice",
        power: 75,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "infestation": {
        id: "infestation",
        name: "Нашествие",
        description: "Насекомые атакуют цель и удерживают её несколько ходов.",
        type: "bug",
        power: 20,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "iron-defense": {
        id: "iron-defense",
        name: "Железная защита",
        description: "Сильно повышает защиту пользователя.",
        type: "steel",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "self",
        effect: "raise_defense_2"
    },
    "jump-kick": {
        id: "jump-kick",
        name: "Прыжковый удар",
        description: "Сильная атака. При промахе пользователь получает отдачу.",
        type: "fighting",
        power: 100,
        accuracy: 95,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_crash"
    },
    "karate-chop": {
        id: "karate-chop",
        name: "Удар карате",
        description: "Физическая атака с повышенным шансом критического удара.",
        type: "fighting",
        power: 50,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "high_crit_damage"
    },
    "leech-seed": {
        id: "leech-seed",
        name: "Паразитные семена",
        description: "Каждый ход вытягивает HP у противника.",
        type: "grass",
        power: 0,
        accuracy: 90,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "leech_seed"
    },
    "lick": {
        id: "lick",
        name: "Лизание",
        description: "Может вызвать паралич.",
        type: "ghost",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "light-screen": {
        id: "light-screen",
        name: "Световой экран",
        description: "Ослабляет особые атаки по вашей стороне поля.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "team",
        effect: "light_screen"
    },
    "low-kick": {
        id: "low-kick",
        name: "Подсечка",
        description: "Сила атаки зависит от веса цели.",
        type: "fighting",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "weight_based_damage"
    },
    "meditate": {
        id: "meditate",
        name: "Медитация",
        description: "Повышает атаку пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "self",
        effect: "raise_attack"
    },
    "mega-drain": {
        id: "mega-drain",
        name: "Мега-поглощение",
        description: "Поглощает HP противника и восстанавливает пользователя.",
        type: "grass",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "drain"
    },
    "mega-kick": {
        id: "mega-kick",
        name: "Мега-пинок",
        description: "Очень сильная физическая атака ногой.",
        type: "normal",
        power: 120,
        accuracy: 75,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "mega-punch": {
        id: "mega-punch",
        name: "Мега-удар",
        description: "Сильная физическая атака кулаком.",
        type: "normal",
        power: 80,
        accuracy: 85,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "megahorn": {
        id: "megahorn",
        name: "Мегарог",
        description: "Очень сильная атака рогом.",
        type: "bug",
        power: 120,
        accuracy: 85,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "metal-claw": {
        id: "metal-claw",
        name: "Металлический коготь",
        description: "Может повысить атаку пользователя.",
        type: "steel",
        power: 50,
        accuracy: 95,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_attack_chance"
    },
    "mimic": {
        id: "mimic",
        name: "Мимикрия",
        description: "Копирует один из приёмов цели.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "copy_move"
    },
    "minimize": {
        id: "minimize",
        name: "Уменьшение",
        description: "Повышает уклонение пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "self",
        effect: "raise_evasion"
    },
    "mirror-coat": {
        id: "mirror-coat",
        name: "Зеркальная оболочка",
        description: "Возвращает полученный особый урон с усилением.",
        type: "psychic",
        power: 0,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: -5,
        target: "enemy",
        effect: "counter_special"
    },
    "mist": {
        id: "mist",
        name: "Туманная завеса",
        description: "Защищает команду от понижения характеристик.",
        type: "ice",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "team",
        effect: "mist"
    },
    "morning-sun": {
        id: "morning-sun",
        name: "Утреннее солнце",
        description: "Восстанавливает HP пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "self",
        effect: "heal"
    },
    "night-shade": {
        id: "night-shade",
        name: "Ночная тень",
        description: "Наносит фиксированный урон, равный уровню пользователя.",
        type: "ghost",
        power: 0,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "fixed_level"
    },
    "outrage": {
        id: "outrage",
        name: "Ярость",
        description: "Атакует несколько ходов подряд, затем вызывает замешательство.",
        type: "dragon",
        power: 120,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "locked_confuse"
    }
});


Object.assign(MOVES, {
    "pain-split": {
        id: "pain-split",
        name: "Разделение боли",
        description: "Делит текущее HP пользователя и цели между ними.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "pain_split"
    },
    "pay-day": {
        id: "pay-day",
        name: "Деньги вперёд",
        description: "Атакует и после боя приносит дополнительные деньги.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_money_bonus"
    },
    "peck": {
        id: "peck",
        name: "Клевок",
        description: "Простая летающая атака клювом.",
        type: "flying",
        power: 35,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "perish-song": {
        id: "perish-song",
        name: "Песнь погибели",
        description: "Через несколько ходов все услышавшие песню покемоны падают.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "field",
        effect: "perish_song"
    },
    "petal-dance": {
        id: "petal-dance",
        name: "Танец лепестков",
        description: "Атакует несколько ходов подряд, затем вызывает замешательство.",
        type: "grass",
        power: 120,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "locked_confuse"
    },
    "pin-missile": {
        id: "pin-missile",
        name: "Игольчатая ракета",
        description: "Бьёт несколько раз подряд.",
        type: "bug",
        power: 25,
        accuracy: 95,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "multi_hit"
    },
    "poison-powder": {
        id: "poison-powder",
        name: "Ядовитая пыльца",
        description: "Отравляет противника.",
        type: "poison",
        power: 0,
        accuracy: 75,
        category: "status",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "poison"
    },
    "poison-sting": {
        id: "poison-sting",
        name: "Ядовитое жало",
        description: "Может отравить противника.",
        type: "poison",
        power: 15,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "pound": {
        id: "pound",
        name: "Шлепок",
        description: "Простая физическая атака.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "powder-snow": {
        id: "powder-snow",
        name: "Снежная пыль",
        description: "Может заморозить противника.",
        type: "ice",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "present": {
        id: "present",
        name: "Подарок",
        description: "Необычный приём, который может либо атаковать, либо лечить цель.",
        type: "normal",
        power: 0,
        accuracy: 90,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "present"
    },
    "protect": {
        id: "protect",
        name: "Защита",
        description: "Полностью защищает пользователя от большинства атак на один ход.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 4,
        target: "self",
        effect: "protect"
    },
    "psybeam": {
        id: "psybeam",
        name: "Психолуч",
        description: "Может вызвать замешательство у цели.",
        type: "psychic",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_confuse_chance"
    },
    "psych-up": {
        id: "psych-up",
        name: "Психоподъём",
        description: "Копирует изменения характеристик цели.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "copy_stat_changes"
    },
    "psywave": {
        id: "psywave",
        name: "Психоволна",
        description: "Наносит случайный урон, зависящий от уровня пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "random_level_damage"
    },
    "rain-dance": {
        id: "rain-dance",
        name: "Танец дождя",
        description: "Вызывает дождь на несколько ходов.",
        type: "water",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "field",
        effect: "rain"
    },
    "rapid-spin": {
        id: "rapid-spin",
        name: "Быстрое вращение",
        description: "Атакует и снимает некоторые помехи с пользователя.",
        type: "normal",
        power: 50,
        accuracy: 100,
        category: "physical",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "damage_clear_hazards"
    },
    "razor-wind": {
        id: "razor-wind",
        name: "Лезвийный ветер",
        description: "Атака в два хода с повышенным шансом критического удара.",
        type: "normal",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "two_turn_high_crit"
    },
    "recover": {
        id: "recover",
        name: "Восстановление",
        description: "Восстанавливает часть HP пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "self",
        effect: "heal"
    },
    "recycle": {
        id: "recycle",
        name: "Переработка",
        description: "Возвращает ранее использованный предмет.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "self",
        effect: "recycle"
    },
    "reflect": {
        id: "reflect",
        name: "Отражение",
        description: "Ослабляет физические атаки по вашей стороне поля.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "team",
        effect: "reflect"
    },
    "rest": {
        id: "rest",
        name: "Отдых",
        description: "Полностью восстанавливает HP и усыпляет пользователя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "self",
        effect: "rest"
    },
    "reversal": {
        id: "reversal",
        name: "Разворот",
        description: "Чем меньше HP у пользователя, тем сильнее атака.",
        type: "fighting",
        power: 1,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "low_hp_stronger"
    },
    "roar": {
        id: "roar",
        name: "Рёв",
        description: "Прогоняет цель или завершает бой с диким покемоном.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: -6,
        target: "enemy",
        effect: "force_switch"
    },
    "rock-throw": {
        id: "rock-throw",
        name: "Бросок камня",
        description: "Простая каменная атака.",
        type: "rock",
        power: 50,
        accuracy: 90,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "rolling-kick": {
        id: "rolling-kick",
        name: "Кувыркающийся удар",
        description: "Может заставить противника дрогнуть.",
        type: "fighting",
        power: 60,
        accuracy: 85,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "rollout": {
        id: "rollout",
        name: "Накат",
        description: "Атакует несколько ходов подряд, усиливаясь каждый раз.",
        type: "rock",
        power: 30,
        accuracy: 90,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "successive_stronger"
    },
    "safeguard": {
        id: "safeguard",
        name: "Защитный покров",
        description: "Защищает команду от статусных состояний на несколько ходов.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 25,
        priority: 0,
        target: "team",
        effect: "safeguard"
    },
    "sand-attack": {
        id: "sand-attack",
        name: "Песчаная атака",
        description: "Понижает точность противника.",
        type: "ground",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "lower_accuracy"
    },
    "scald": {
        id: "scald",
        name: "Ошпаривание",
        description: "Водная атака, которая может вызвать ожог.",
        type: "water",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "scary-face": {
        id: "scary-face",
        name: "Страшная морда",
        description: "Сильно понижает скорость противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "lower_speed_2"
    },
    "screech": {
        id: "screech",
        name: "Визг",
        description: "Сильно понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 85,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_defense_2"
    },
    "seed-bomb": {
        id: "seed-bomb",
        name: "Семенная бомба",
        description: "Сильная физическая травяная атака.",
        type: "grass",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "seismic-toss": {
        id: "seismic-toss",
        name: "Сейсмический бросок",
        description: "Наносит фиксированный урон, равный уровню пользователя.",
        type: "fighting",
        power: 0,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "fixed_level"
    },
    "self-destruct": {
        id: "self-destruct",
        name: "Самоуничтожение",
        description: "Очень мощная атака, после которой пользователь падает.",
        type: "normal",
        power: 200,
        accuracy: 100,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "self_destruct"
    },
    "sing": {
        id: "sing",
        name: "Пение",
        description: "Усыпляет противника.",
        type: "normal",
        power: 0,
        accuracy: 55,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "sleep"
    },
    "sketch": {
        id: "sketch",
        name: "Эскиз",
        description: "Навсегда копирует последний приём цели.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 1,
        priority: 0,
        target: "enemy",
        effect: "sketch"
    },
    "slash": {
        id: "slash",
        name: "Рассечение",
        description: "Физическая атака с повышенным шансом критического удара.",
        type: "normal",
        power: 70,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "high_crit_damage"
    },
    "sleep-powder": {
        id: "sleep-powder",
        name: "Сонная пыльца",
        description: "Усыпляет противника.",
        type: "grass",
        power: 0,
        accuracy: 75,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "sleep"
    },
    "sludge": {
        id: "sludge",
        name: "Грязь",
        description: "Может отравить противника.",
        type: "poison",
        power: 65,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "smog": {
        id: "smog",
        name: "Смог",
        description: "Может отравить противника.",
        type: "poison",
        power: 30,
        accuracy: 70,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "smokescreen": {
        id: "smokescreen",
        name: "Дымовая завеса",
        description: "Понижает точность противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "lower_accuracy"
    }
});


Object.assign(MOVES, {
    "sonic-boom": {
        id: "sonic-boom",
        name: "Соникбум",
        description: "Всегда наносит фиксированный урон.",
        type: "normal",
        power: 0,
        accuracy: 90,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "fixed_20"
    },
    "spark": {
        id: "spark",
        name: "Искрение",
        description: "Может вызвать паралич.",
        type: "electric",
        power: 65,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "spikes": {
        id: "spikes",
        name: "Шипы",
        description: "Рассыпает шипы на стороне противника.",
        type: "ground",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "field",
        effect: "spikes"
    },
    "spite": {
        id: "spite",
        name: "Злопамятность",
        description: "Уменьшает PP последнего использованного приёма цели.",
        type: "ghost",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "lower_pp"
    },
    "splash": {
        id: "splash",
        name: "Барахтанье",
        description: "Обычно не оказывает никакого эффекта.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "self",
        effect: "no_effect"
    },
    "stomp": {
        id: "stomp",
        name: "Топот",
        description: "Может заставить противника дрогнуть.",
        type: "normal",
        power: 65,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "string-shot": {
        id: "string-shot",
        name: "Нитяной выстрел",
        description: "Понижает скорость противника.",
        type: "bug",
        power: 0,
        accuracy: 95,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_speed"
    },
    "struggle-bug": {
        id: "struggle-bug",
        name: "Жукоборьба",
        description: "Может понизить спецатаку противника.",
        type: "bug",
        power: 50,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spatk_chance"
    },
    "stun-spore": {
        id: "stun-spore",
        name: "Парализующая пыльца",
        description: "Парализует противника.",
        type: "grass",
        power: 0,
        accuracy: 75,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "paralyze"
    },
    "submission": {
        id: "submission",
        name: "Подчинение",
        description: "Сильная физическая атака с отдачей.",
        type: "fighting",
        power: 80,
        accuracy: 80,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_recoil"
    },
    "substitute": {
        id: "substitute",
        name: "Подмена",
        description: "Создаёт замену, которая принимает урон вместо пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "self",
        effect: "substitute"
    },
    "super-fang": {
        id: "super-fang",
        name: "Суперклык",
        description: "Срезает половину текущего HP цели.",
        type: "normal",
        power: 0,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "halve_hp"
    },
    "supersonic": {
        id: "supersonic",
        name: "Ультразвук",
        description: "Приводит цель в замешательство.",
        type: "normal",
        power: 0,
        accuracy: 55,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "confuse"
    },
    "swagger": {
        id: "swagger",
        name: "Хвастовство",
        description: "Сильно повышает атаку цели, но вызывает замешательство.",
        type: "normal",
        power: 0,
        accuracy: 85,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "confuse_raise_attack_2"
    },
    "sweet-kiss": {
        id: "sweet-kiss",
        name: "Сладкий поцелуй",
        description: "Вызывает замешательство у цели.",
        type: "fairy",
        power: 0,
        accuracy: 75,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "confuse"
    },
    "sweet-scent": {
        id: "sweet-scent",
        name: "Сладкий аромат",
        description: "Понижает уклонение противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "lower_evasion"
    },
    "swift": {
        id: "swift",
        name: "Звёздный поток",
        description: "Никогда не промахивается.",
        type: "normal",
        power: 60,
        accuracy: 101,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    },
    "swords-dance": {
        id: "swords-dance",
        name: "Танец мечей",
        description: "Сильно повышает атаку пользователя.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "self",
        effect: "raise_attack_2"
    },
    "synthesis": {
        id: "synthesis",
        name: "Синтез",
        description: "Восстанавливает HP пользователя.",
        type: "grass",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 5,
        priority: 0,
        target: "self",
        effect: "heal"
    },
    "take-down": {
        id: "take-down",
        name: "Таран",
        description: "Физическая атака с отдачей.",
        type: "normal",
        power: 90,
        accuracy: 85,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_recoil"
    },
    "teleport": {
        id: "teleport",
        name: "Телепорт",
        description: "Позволяет немедленно покинуть поле боя.",
        type: "psychic",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: -6,
        target: "self",
        effect: "escape"
    },
    "thief": {
        id: "thief",
        name: "Кража",
        description: "Наносит урон и может украсть предмет цели.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_steal_item"
    },
    "thrash": {
        id: "thrash",
        name: "Буйство",
        description: "Атакует несколько ходов подряд, затем вызывает замешательство.",
        type: "normal",
        power: 120,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "locked_confuse"
    },
    "thunder-punch": {
        id: "thunder-punch",
        name: "Громовой кулак",
        description: "Электрическая атака кулаком. Может вызвать паралич.",
        type: "electric",
        power: 75,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "thunder-wave": {
        id: "thunder-wave",
        name: "Громовая волна",
        description: "Парализует противника.",
        type: "electric",
        power: 0,
        accuracy: 90,
        category: "status",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "paralyze"
    },
    "torment": {
        id: "torment",
        name: "Мучение",
        description: "Не позволяет цели использовать один и тот же приём два хода подряд.",
        type: "dark",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "torment"
    },
    "toxic": {
        id: "toxic",
        name: "Токсин",
        description: "Сильно отравляет противника.",
        type: "poison",
        power: 0,
        accuracy: 90,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "bad_poison"
    },
    "transform": {
        id: "transform",
        name: "Трансформация",
        description: "Копирует форму, характеристики и приёмы цели.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "transform"
    },
    "tri-attack": {
        id: "tri-attack",
        name: "Тройная атака",
        description: "Может вызвать ожог, паралич или заморозку.",
        type: "normal",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_tri_status_chance"
    },
    "twineedle": {
        id: "twineedle",
        name: "Двойное жало",
        description: "Бьёт два раза и может отравить.",
        type: "bug",
        power: 25,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_2_poison_chance"
    },
    "twister": {
        id: "twister",
        name: "Смерч",
        description: "Может заставить противника дрогнуть.",
        type: "dragon",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "vice-grip": {
        id: "vice-grip",
        name: "Клещи",
        description: "Простая физическая атака захватом.",
        type: "normal",
        power: 55,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "whirlpool": {
        id: "whirlpool",
        name: "Водоворот",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "water",
        power: 35,
        accuracy: 85,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "whirlwind": {
        id: "whirlwind",
        name: "Вихрь",
        description: "Прогоняет цель или завершает бой с диким покемоном.",
        type: "normal",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 20,
        priority: -6,
        target: "enemy",
        effect: "force_switch"
    },
    "wing-attack": {
        id: "wing-attack",
        name: "Крыло-удар",
        description: "Простая летающая физическая атака.",
        type: "flying",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "withdraw": {
        id: "withdraw",
        name: "Втягивание",
        description: "Повышает защиту пользователя.",
        type: "water",
        power: 0,
        accuracy: 101,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "self",
        effect: "raise_defense"
    },
    "wrap": {
        id: "wrap",
        name: "Обвивание",
        description: "Наносит урон и может удерживать цель несколько ходов.",
        type: "normal",
        power: 15,
        accuracy: 90,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_trap"
    },
    "zap-cannon": {
        id: "zap-cannon",
        name: "Электропушка",
        description: "Мощная электрическая атака, которая гарантированно парализует при попадании.",
        type: "electric",
        power: 120,
        accuracy: 50,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze"
    }
});

function getMoveDescription(moveId) {
    if (!MOVES[moveId]) return "Описание отсутствует.";
    return MOVES[moveId].description || "Описание отсутствует.";
}
