// =======================================================================
// БАЗА ПРИЁМОВ POKEMON
// Этап 1: стартовый централизованный справочник
// =======================================================================

const MOVES = {
    "tackle": {
        id: "tackle",
        name: "Удар",
        description: "Обычная физическая атака без дополнительного эффекта.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "vine-whip": {
        id: "vine-whip",
        name: "Семенной луч",
        description: "Покемон бьёт врага лозой.",
        type: "grass",
        power: 45,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "growl": {
        id: "growl",
        name: "Рык",
        description: "Понижает атаку противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 40,
        priority: 0,
        target: "enemy",
        effect: "lower_attack"
    },
    "ember": {
        id: "ember",
        name: "Уголёк",
        description: "Небольшая огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "water-gun": {
        id: "water-gun",
        name: "Водяной пистолет",
        description: "Атака струёй воды.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "thunder-shock": {
        id: "thunder-shock",
        name: "Искрошок",
        description: "Электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "scratch": {
        id: "scratch",
        name: "Царапина",
        description: "Покемон царапает врага когтями.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 35,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "leer": {
        id: "leer",
        name: "Злобный взгляд",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    },
    "bite": {
        id: "bite",
        name: "Укус",
        description: "Кусает противника. Может заставить дрогнуть.",
        type: "dark",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "quick-attack": {
        id: "quick-attack",
        name: "Быстрая атака",
        description: "Атакует раньше обычного.",
        type: "normal",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 1,
        target: "enemy",
        effect: "damage"
    },
    "razor-leaf": {
        id: "razor-leaf",
        name: "Острый лист",
        description: "Режет врага острыми листьями.",
        type: "grass",
        power: 55,
        accuracy: 95,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "flame-wheel": {
        id: "flame-wheel",
        name: "Огненное колесо",
        description: "Атака в огненном вращении. Может вызвать ожог.",
        type: "fire",
        power: 60,
        accuracy: 100,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "bubble": {
        id: "bubble",
        name: "Пузырь",
        description: "Атака пузырями. Может понизить скорость.",
        type: "water",
        power: 40,
        accuracy: 100,
        category: "special",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_speed_chance"
    },
    "thunderbolt": {
        id: "thunderbolt",
        name: "Удар молнии",
        description: "Мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "fire-blast": {
        id: "fire-blast",
        name: "Огненный взрыв",
        description: "Очень мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 110,
        accuracy: 85,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "hydro-pump": {
        id: "hydro-pump",
        name: "Гидронасос",
        description: "Очень мощная водная атака.",
        type: "water",
        power: 110,
        accuracy: 80,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "solar-beam": {
        id: "solar-beam",
        name: "Солнечный луч",
        description: "Мощная травяная атака.",
        type: "grass",
        power: 120,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "psychic": {
        id: "psychic",
        name: "Психический",
        description: "Мощная психическая атака. Может понизить спецзащиту.",
        type: "psychic",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "shadow-ball": {
        id: "shadow-ball",
        name: "Теневой шар",
        description: "Атака теневой сферой. Может понизить спецзащиту.",
        type: "ghost",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "hyper-beam": {
        id: "hyper-beam",
        name: "Гиперлуч",
        description: "Очень мощная атака. После неё нужен отдых.",
        type: "normal",
        power: 150,
        accuracy: 90,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_recharge"
    },
    "flamethrower": {
        id: "flamethrower",
        name: "Огнемёт",
        description: "Мощная огненная атака. Может вызвать ожог.",
        type: "fire",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_burn_chance"
    },
    "ice-beam": {
        id: "ice-beam",
        name: "Ледяной луч",
        description: "Мощная ледяная атака. Может заморозить.",
        type: "ice",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_freeze_chance"
    },
    "thunder": {
        id: "thunder",
        name: "Гром",
        description: "Очень мощная электрическая атака. Может вызвать паралич.",
        type: "electric",
        power: 110,
        accuracy: 70,
        category: "special",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage_paralyze_chance"
    },
    "earthquake": {
        id: "earthquake",
        name: "Землетрясение",
        description: "Мощная атака землёй.",
        type: "ground",
        power: 100,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "surf": {
        id: "surf",
        name: "Прилив",
        description: "Мощная водная атака.",
        type: "water",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "fly": {
        id: "fly",
        name: "Полёт",
        description: "Атака с взлётом и ударом.",
        type: "flying",
        power: 90,
        accuracy: 95,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "dig": {
        id: "dig",
        name: "Копание",
        description: "Атака с уходом под землю.",
        type: "ground",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "two_turn_damage"
    },
    "strength": {
        id: "strength",
        name: "Сила",
        description: "Мощная физическая атака.",
        type: "normal",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "cut": {
        id: "cut",
        name: "Разрез",
        description: "Режущая обычная атака.",
        type: "normal",
        power: 50,
        accuracy: 95,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "rock-smash": {
        id: "rock-smash",
        name: "Крушение камня",
        description: "Физическая атака. Может понизить защиту.",
        type: "fighting",
        power: 40,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "shadow-punch": {
        id: "shadow-punch",
        name: "Теневой удар",
        description: "Теневая атака, которая не промахивается.",
        type: "ghost",
        power: 60,
        accuracy: 101,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "never_miss_damage"
    },
    "dragon-claw": {
        id: "dragon-claw",
        name: "Коготь дракона",
        description: "Сильная драконья атака.",
        type: "dragon",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "dark-pulse": {
        id: "dark-pulse",
        name: "Тёмный импульс",
        description: "Тёмная атака. Может заставить дрогнуть.",
        type: "dark",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "dazzling-gleam": {
        id: "dazzling-gleam",
        name: "Ослепительное сияние",
        description: "Атака волшебным светом.",
        type: "fairy",
        power: 80,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "moonblast": {
        id: "moonblast",
        name: "Лунный взрыв",
        description: "Мощная волшебная атака. Может понизить спецатаку.",
        type: "fairy",
        power: 95,
        accuracy: 100,
        category: "special",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spatk_chance"
    },
    "play-rough": {
        id: "play-rough",
        name: "Игривый удар",
        description: "Может понизить атаку противника.",
        type: "fairy",
        power: 90,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_attack_chance"
    },
    "x-scissor": {
        id: "x-scissor",
        name: "Икс-ножницы",
        description: "Сильная режущая атака.",
        type: "bug",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "bug-buzz": {
        id: "bug-buzz",
        name: "Жужжание",
        description: "Звуковая атака насекомого. Может понизить спецзащиту.",
        type: "bug",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_spdef_chance"
    },
    "poison-jab": {
        id: "poison-jab",
        name: "Ядовитый укол",
        description: "Может отравить противника.",
        type: "poison",
        power: 80,
        accuracy: 100,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "sludge-bomb": {
        id: "sludge-bomb",
        name: "Грязевая бомба",
        description: "Может отравить противника.",
        type: "poison",
        power: 90,
        accuracy: 100,
        category: "special",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_poison_chance"
    },
    "steel-wing": {
        id: "steel-wing",
        name: "Стальное крыло",
        description: "Может повысить защиту пользователя.",
        type: "steel",
        power: 70,
        accuracy: 90,
        category: "physical",
        max_pp: 25,
        priority: 0,
        target: "enemy",
        effect: "damage_raise_defense_chance"
    },
    "iron-tail": {
        id: "iron-tail",
        name: "Железный хвост",
        description: "Может понизить защиту противника.",
        type: "steel",
        power: 100,
        accuracy: 75,
        category: "physical",
        max_pp: 15,
        priority: 0,
        target: "enemy",
        effect: "damage_lower_defense_chance"
    },
    "rock-slide": {
        id: "rock-slide",
        name: "Камнепад",
        description: "Может заставить противника дрогнуть.",
        type: "rock",
        power: 75,
        accuracy: 90,
        category: "physical",
        max_pp: 10,
        priority: 0,
        target: "enemy",
        effect: "damage_flinch_chance"
    },
    "stone-edge": {
        id: "stone-edge",
        name: "Каменный край",
        description: "Сильная каменная атака.",
        type: "rock",
        power: 100,
        accuracy: 80,
        category: "physical",
        max_pp: 5,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "slam": {
        id: "slam",
        name: "Шлепок",
        description: "Сильная обычная атака.",
        type: "normal",
        power: 80,
        accuracy: 75,
        category: "physical",
        max_pp: 20,
        priority: 0,
        target: "enemy",
        effect: "damage"
    },
    "double-kick": {
        id: "double-kick",
        name: "Двойной удар",
        description: "Бьёт два раза подряд.",
        type: "fighting",
        power: 30,
        accuracy: 100,
        category: "physical",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "multi_hit_2"
    },
    "tail-whip": {
        id: "tail-whip",
        name: "Виляние хвостом",
        description: "Понижает защиту противника.",
        type: "normal",
        power: 0,
        accuracy: 100,
        category: "status",
        max_pp: 30,
        priority: 0,
        target: "enemy",
        effect: "lower_defense"
    }
};

function getMoveDescription(moveId) {
    if (!MOVES[moveId]) return "Описание отсутствует.";
    return MOVES[moveId].description || "Описание отсутствует.";
}
